version: "3.9"
services:
  web:
    build: frontend
    ports:
      - "${WEB_PORT}:3000"
    env_file:
      - .env
    links:
      - middleware
    volumes:
      - ./frontend/src:/app/src
  middleware:
    build: middleware
    ports:
      - "8080:8080"
    links:
      - ml_decision_server
    environment:
      - ML_SERVER_URL=http://ml_decision_server:5000
      - MENTOR_URL=http://protectddos:5001
    networks:
      - backend
  ml_decision_server:
    image: sulasdelii/risk_classifier:latest
    expose:
      - "5000"
    networks:
      - backend
  ml_models_management:
    image: bentoml/yatai-service:latest
    env_file:
      - .env
    command:
      - --db-url=${DB_URL}
      - --repo-base-url=${REPO_BASE_URL}
    volumes:
      - ${BENTO_HOME}:/bentoml
    ports:
      - "50051:50051"
      - "3000:3000"
  protectddos:
    image: sulasdelii/protectddos:latest
    expose:
      - "5001"
    networks:
      - backend
  api:
    build: api
    ports:
      - "8000:8000"
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - ./api:/api
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prototype
    networks:
      - backend
    ports:
      - "54321:5432"

networks:
  backend:
volumes:
  postgres_data: