"""remove title in Eventlog

Revision ID: 2a908ddef9bd
Revises: b5d95b531542
Create Date: 2022-03-18 02:53:13.764642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a908ddef9bd'
down_revision = 'b5d95b531542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventlog_files', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventlog_files', sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
