"""Adding ProcessNaning to othe model

Revision ID: b5d95b531542
Revises: 16b5972b976e
Create Date: 2022-03-17 20:37:06.291851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d95b531542'
down_revision = '16b5972b976e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery', sa.Column('process_id', sa.Integer(), nullable=True))
    op.add_column('discovery', sa.Column('name', sa.String(length=128), nullable=True))
    op.create_foreign_key('discovery_process_id_fkey', 'discovery', 'process_naming', ['process_id'], ['id'])
    op.add_column('eventlog_files', sa.Column('process_id', sa.Integer(), nullable=True))
    op.drop_constraint('eventlog_files_user_id_fkey', 'eventlog_files', type_='foreignkey')
    op.create_foreign_key('eventlog_files_process_id_fkey', 'eventlog_files', 'process_naming', ['process_id'], ['id'])
    op.drop_column('eventlog_files', 'profile_id')
    op.add_column('statistic', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('statistic', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('statistic', 'handover_of_work')
    op.add_column('statistic', sa.Column('handover_of_work', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'handover_of_work')
    op.add_column('statistic', sa.Column('handover_of_work', sa.TEXT(), nullable=True))
    op.drop_column('statistic', 'updated_at')
    op.drop_column('statistic', 'created_at')
    op.add_column('eventlog_files', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('eventlog_files_process_id_fkey', 'eventlog_files', type_='foreignkey')
    op.create_foreign_key('eventlog_files_user_id_fkey', 'eventlog_files', 'profile', ['profile_id'], ['id'])
    op.drop_column('eventlog_files', 'process_id')
    op.drop_constraint('discovery_process_id_fkey', 'discovery', type_='foreignkey')
    op.drop_column('discovery', 'name')
    op.drop_column('discovery', 'process_id')
    # ### end Alembic commands ###
