"""update Underwriting table

Revision ID: bcc1452f7fff
Revises: 68ff0b272263
Create Date: 2022-03-19 18:23:12.359944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcc1452f7fff'
down_revision = '68ff0b272263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_modifiers')
    op.add_column('underwritings', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.add_column('underwritings', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.create_foreign_key('underwritings_profile_id_fkey', 'underwritings', 'profile', ['profile_id'], ['id'])
    op.drop_column('underwritings', 'customer_id')
    op.drop_column('underwritings', 'customer_name')
    op.drop_column('underwritings', 'assessment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('underwritings', sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('underwritings', sa.Column('customer_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('underwritings', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('underwritings_profile_id_fkey', 'underwritings', type_='foreignkey')
    op.drop_column('underwritings', 'edited_at')
    op.drop_column('underwritings', 'profile_id')
    op.create_table('risk_modifiers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('policy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name='risk_modifiers_policy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='risk_modifiers_pkey')
    )
    # ### end Alembic commands ###
